#!/bin/bash

# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
# execute all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.

set -eu

echo "0. Boostrapping"

echo "creating symlinks to config files"
if eval "yadm alt"; then

  # Directory to look for bootstrap executables in
  BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
  if [[ ! -d "$BOOTSTRAP_D" ]]; then
    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
    exit 1
  fi

  if eval "$BOOTSTRAP_D/bootstrap"; then
    echo "Bootstrapping Complete"
  else
    echo "Bootstrapping Failed. exiting."
    exit 1
  fi

else
  echo "failed to create symlinks. exiting."
  exit 1
fi
