#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom&

mons -a -e right&

dunst&

killall -q polybar

  for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar example&
  done

feh --bg-fill --randomize ~/.wallpapers/*

xinput set-prop "1A582000:00 06CB:CD73 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "1A582000:00 06CB:CD73 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "1A582000:00 06CB:CD73 Touchpad" "libinput Middle Emulation Enabled" 1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config active_border_color \#4C566A
bspc config normal_border_color \#2E3440
